- name: check if migration_tools exists
  stat:
    path: "{{ local_distr_path }}/migration_tools"
  register: result
  delegate_to: localhost

- name: install migration tools
  block:

    - name: create migration directory
      file:
        path: "{{ PGHOME }}/migration_tools"
        state: directory
        owner: postgres
        group: postgres
        mode: 0700

    - name: copy migration_tools to nodes
      copy:
        src: "{{ item }}"
        dest: "{{ PGHOME }}/migration_tools"
      with_items:
        - "{{ local_distr_path }}/migration_tools/db-data-comparator"
        - "{{ local_distr_path }}/migration_tools/ora2pg"
        - "{{ local_distr_path }}/migration_tools/pgloader"

  become: true
  become_user: postgres
  when: result.stat.exists
