#TODO PGSQL-4559
- name: Prepare using encrypt space for patroni
  block:

    - name: remove cert for patroni using
      lineinfile:
        path: "{{ patroni_files.conf_dir }}/postgres.yml"
        state: absent
        regexp: "{{ item.rexexp }}"
      loop:
        - { rexexp: ".*sslmode:.*"}
        - { rexexp: ".*sslkey:.*$" }
        - { rexexp: ".*sslcert:.*$" }
        - { rexexp: ".*sslrootcert:.*$" }

    - name: remove postgres replication
      lineinfile:
        path: "{{ patroni_files.conf_dir }}/postgres.yml"
        regexp: "replication postgres"
        state: absent

    - name: update user for restapi and etcd
      replace:
        path: "{{ patroni_files.conf_dir }}/postgres.yml"
        after: "{{ item.after }}"
        regexp: "{{ item.rexexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { after: "replication:", rexexp: "^(.*)            username: postgres", replace: '            username: patroni'}
        - { after: "superuser:", rexexp: "^(.*)              username: postgres", replace: '            username: patroni'}

    - name: update password for restapi and etcd
      lineinfile:
        path: "{{ patroni_files.conf_dir }}/postgres.yml"
        insertafter: 'replication:'
        line: '            database: replication'

  become: true
  become_user: postgres
  when: "'patroni' in tag and inventory_hostname != 'etcd'"