- name: Encrypt password
  shell: |
    spawn {{ PGHOME }}/bin/pg_auth_password enc -s
    expect "enter password:"
    send  "{{ password | escape_string }}\r"
    expect eof
  register: _createencryptpass_password
  args:
    executable: "expect"
  environment:
    PG_PLUGINS_PATH: "{{ PGHOME }}/lib"
  no_log: "{{ nolog }}"
  become: true
  become_user: postgres

- name: Save encrypt password
  set_fact:
    _createencryptpass_password: "{{_createencryptpass_password.stdout_lines[3]}}"
  no_log: "{{ nolog }}"