- name: Install Altlinux MC
  shell: sudo apt-get install mc -y

- name: Install Altlinux unzip
  shell: sudo apt-get install unzip -y

- name: Install Altlinux Python
  shell: sudo apt-get install python -y

- name: Install Altlinux Nginx
  shell: sudo apt-get install nginx -y