- set_fact:
    db_files_fs: "/{{ PGDATA.replace('/', ' ').split().0 }}"
    db_logs_fs: "/{{ PGBACKUP.replace('/', ' ').split().0 }}"
    db_pg_data_fs: "/{{ PGDATA.replace('/', ' ').split().0 }}"

- name: Find clustername in /etc/opt/omni/server/cell/devfilters
  block:
    - shell: "cat /etc/opt/omni/server/cell/devfilters | grep -i '{{ cluster }}'"
      changed_when: false
      register: di
  rescue:
    - shell: "cat /etc/opt/omni/server/cell/devfilters | grep -i 'default'"
      changed_when: false
      register: di

- set_fact:
    keyword_stdout: "{{ di }}"

- set_fact:
    device: "{{ keyword_stdout.stdout_lines[0].split().0 }}"
    mi: "{{ '%02d' | format( 59 | random | int ) }}"

- block:
    - name: Add new host to data-protector
      shell: "sudo /opt/omni/bin/omnicc -export_host {{ item }}"
      failed_when: false
      changed_when: false
      args:
        warn: no
      register: export_host
      with_items: 
        - "{{ master_hostname }}"
        - "{{ replica_hostname }}"

    - name: Configure data-protector for new host
      shell: "sudo /opt/omni/bin/omnicc -secure_comm -configure_for_dr {{ item }} -accept_host"
      args:
        warn: no
      with_items: 
        - "{{ master_hostname }}"
        - "{{ replica_hostname }}"

    - name: Add new host to data-protector
      shell: "sudo /opt/omni/bin/omnicc -import_host {{ item }} -accept_host"
      args:
        warn: no
      with_items: 
        - "{{ master_hostname }}"
        - "{{ replica_hostname }}"

    - name: Create datalists
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "datalist_serveraXserverb_servera_PG_FULL.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ master_hostname }}_PG_FULL" }
        - { src: "datalist_serveraXserverb_serverb_PG_FULL.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ replica_hostname }}_PG_FULL" }
        - { src: "datalist_serveraXserverb_servera_PG_LOG.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ master_hostname }}_PG_LOG" }
        - { src: "datalist_serveraXserverb_serverb_PG_LOG.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ replica_hostname }}_PG_LOG" }
        - { src: "datalist_serveraXserverb_RUN_PG_FULL.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}X{{ replica_hostname }}_RUN_PG_FULL" }

    - name: Create schedule files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "schedule_serveraXserverb_servera_PG_FULL.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ master_hostname }}_PG_FULL" }
        - { src: "schedule_serveraXserverb_serverb_PG_FULL.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ replica_hostname }}_PG_FULL" }
        - { src: "schedule_serveraXserverb_servera_PG_LOG.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ master_hostname }}_PG_LOG" }
        - { src: "schedule_serveraXserverb_serverb_PG_LOG.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}X{{ replica_hostname }}\
            _{{ replica_hostname }}_PG_LOG" }
        - { src: "schedule_serveraXserverb_RUN_PG_FULL.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}X{{ replica_hostname }}_RUN_PG_FULL" }
  when: installation_type == 'cluster'

- block:
    - name: Add new host to data-protector
      shell: "sudo /opt/omni/bin/omnicc -export_host {{ master_hostname }}"
      failed_when: false
      changed_when: false
      args:
        warn: no
      register: export_host

    - name: Configure data-protector for new host
      shell: "sudo /opt/omni/bin/omnicc -secure_comm -configure_for_dr {{ master_hostname }} -accept_host"
      args:
        warn: no

    - name: Add new host to data-protector
      shell: "sudo /opt/omni/bin/omnicc -import_host {{ master_hostname }} -accept_host"
      args:
        warn: no

    - name: Create datalists
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "datalist_standalone_PG_FULL.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}_PG_FULL" }
        - { src: "datalist_standalone_PG_LOG.j2", dest: "/etc/opt/omni/server/datalists/{{ master_hostname }}_PG_LOG" }

    - name: Create schedule files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "schedule_serveraXserverb_RUN_PG_FULL.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}_PG_FULL" }
        - { src: "schedule_serveraXserverb_servera_PG_LOG.j2", dest: "/etc/opt/omni/server/schedules/{{ master_hostname }}_PG_LOG" }
  when: installation_type == 'standalone'
